# Generated by Django 5.2.1 on 2025-07-19 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('cta_annotation', models.CharField(blank=True, max_length=500)),
                ('cta_button_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.URLField(blank=True)),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero_block', to='landings.landingpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BenefitsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text1', models.CharField(max_length=255)),
                ('svg_icon1', models.TextField(blank=True)),
                ('text2', models.CharField(max_length=255)),
                ('svg_icon2', models.TextField(blank=True)),
                ('text3', models.CharField(max_length=255)),
                ('is_gallery3', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='benefits/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='benefits/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='benefits/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='benefits/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='benefits/')),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefits_block', to='landings.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='landings.landingpage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
