# Generated by Django 5.2.1 on 2025-07-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroblock',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SolutionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('utp', models.CharField(max_length=255)),
                ('cta_button_text', models.CharField(blank=True, max_length=100)),
                ('text1', models.CharField(max_length=255)),
                ('svg_icon1', models.TextField(blank=True)),
                ('text2', models.CharField(max_length=255)),
                ('svg_icon2', models.TextField(blank=True)),
                ('text3', models.CharField(max_length=255)),
                ('svg_icon3', models.TextField(blank=True)),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solutions_block', to='landings.landingpage')),
            ],
        ),
    ]
