# Generated by Django 5.2.1 on 2025-07-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0002_heroblock_active_solutionsblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitsblock',
            name='title',
        ),
        migrations.AddField(
            model_name='benefitsblock',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='benefitsblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solutionsblock',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solutionsblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solutionsblock',
            name='title',
            field=models.CharField(blank=True, default='Столкнулись с проблемами?', max_length=255),
        ),
        migrations.DeleteModel(
            name='TextBlock',
        ),
    ]
