# Generated by Django 5.2.1 on 2025-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0003_remove_benefitsblock_title_benefitsblock_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroblock',
            name='cta_annotation',
            field=models.CharField(blank=True, default='Закажите проект под ключ для инвесторов', max_length=500),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Заказать проект', max_length=100),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='subtitle',
            field=models.CharField(blank=True, default='Получите готовый бизнес-план для успешного старта и привлечения инвестиций!', max_length=500),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='title',
            field=models.CharField(default='Astana <br>Business–Plan', max_length=255),
        ),
    ]
