# Generated by Django 5.2.1 on 2025-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0004_alter_heroblock_cta_annotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitsblock',
            name='text1',
            field=models.CharField(max_length=255, verbose_name='test'),
        ),
    ]
