# Generated by Django 5.2.1 on 2025-07-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0006_alter_benefitsblock_svg_icon1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Наши тарифы', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='Выберите подходящий тариф', max_length=255)),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_block', to='landings.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='TariffCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(max_length=100)),
                ('button_text', models.CharField(default='Выбрать тариф', max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('accent', models.BooleanField(default=False, help_text='Сделать карточку акцентной (выделенной)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='landings.tariffblock')),
            ],
        ),
        migrations.CreateModel(
            name='TariffProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Свойство')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landings.tariffcard')),
            ],
        ),
    ]
