# Generated by Django 5.2.1 on 2025-07-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0007_tariffblock_tariffcard_tariffproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffcard',
            name='svg_icon',
            field=models.TextField(blank=True, default='empty'),
        ),
    ]
