# Generated by Django 5.2.1 on 2025-07-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0009_tariffproperty_is_check_alter_tariffcard_svg_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffblock',
            name='current',
            field=models.CharField(blank=True, default='₸', max_length=3),
        ),
    ]
