# Generated by Django 5.2.1 on 2025-07-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0010_tariffblock_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffblock',
            name='subtitle',
        ),
    ]
