# Generated by Django 5.2.1 on 2025-07-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0011_remove_tariffblock_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True)),
                ('subtitle', models.CharField(default='О нас', max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_bock', to='landings.landingpage')),
            ],
        ),
    ]
