# Generated by Django 5.2.1 on 2025-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0012_aboutblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutblock',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
