# Generated by Django 5.2.1 on 2025-07-20 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0013_aboutblock_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutblock',
            name='landing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_block', to='landings.landingpage'),
        ),
    ]
