# Generated by Django 5.2.1 on 2025-07-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0014_alter_aboutblock_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutblock',
            name='button_text',
            field=models.CharField(default='Получить консультацию', max_length=100),
        ),
    ]
