# Generated by Django 5.2.1 on 2025-07-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0015_aboutblock_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, verbose_name='Cases')),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cases_block', to='landings.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='CasesBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_items', to='landings.casesblock')),
            ],
        ),
    ]
