# Generated by Django 5.2.1 on 2025-07-20 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0016_casesblock_casesblockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesblockitem',
            name='cases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='landings.casesblock'),
        ),
    ]
