# Generated by Django 5.2.1 on 2025-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0017_alter_casesblockitem_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesblockitem',
            name='current',
            field=models.CharField(blank=True, default='₸', max_length=3),
        ),
    ]
