# Generated by Django 5.2.1 on 2025-07-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0018_casesblockitem_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Cases')),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_block', to='landings.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificate/')),
                ('title', models.CharField(blank=True, default=None, max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='landings.certificateblock')),
            ],
        ),
    ]
