# Generated by Django 5.2.1 on 2025-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0019_certificateblock_certificateblockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateblock',
            name='title',
            field=models.CharField(default='Certificates', max_length=100, verbose_name='Certificares'),
        ),
    ]
