# Generated by Django 5.2.1 on 2025-07-20 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0021_alter_certificateblock_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateblock',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClientsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients_block', to='landings.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='ClientsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='landings.clientsblock')),
            ],
        ),
    ]
