# Generated by Django 5.2.1 on 2025-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0022_certificateblock_active_clientsblock_clientslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsblock',
            name='clients_list',
            field=models.TextField(blank=True, verbose_name='Список клиентов (каждый с новой строки)'),
        ),
        migrations.DeleteModel(
            name='ClientsList',
        ),
    ]
