# Generated by Django 5.2.1 on 2025-07-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0023_clientsblock_clients_list_delete_clientslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='FAQ', max_length=255)),
                ('landing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_block', to='landings.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='FaqBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='landings.faqblock')),
            ],
        ),
    ]
