# Generated by Django 5.2.1 on 2025-07-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0024_faqblock_faqblockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqblockitem',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='landings.faqblock'),
        ),
    ]
