# Generated by Django 5.2.1 on 2025-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0026_aboutblock_slug_benefitsblock_slug_casesblock_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitsblock',
            name='slug',
            field=models.SlugField(blank=True, default='benefits', max_length=250),
        ),
    ]
