# Generated by Django 5.2.1 on 2025-07-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0027_alter_benefitsblock_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefitsblock',
            name='order',
        ),
        migrations.RemoveField(
            model_name='solutionsblock',
            name='order',
        ),
        migrations.AddField(
            model_name='benefitsblock',
            name='title',
            field=models.CharField(default='Benefits ingo', max_length=255),
        ),
    ]
