# Generated by Django 5.2.1 on 2025-07-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0028_remove_benefitsblock_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroblock',
            options={},
        ),
        migrations.RemoveField(
            model_name='heroblock',
            name='order',
        ),
    ]
