# Generated by Django 5.2.1 on 2025-07-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0029_alter_heroblock_options_remove_heroblock_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitsblock',
            name='slug',
            field=models.SlugField(blank=True, default='benefits', max_length=250, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='benefitsblock',
            name='title',
            field=models.CharField(default='Benefits info', max_length=255),
        ),
    ]
