# Generated by Django 5.2.1 on 2025-07-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0030_alter_benefitsblock_slug_alter_benefitsblock_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitsblock',
            name='slug',
            field=models.SlugField(blank=True, default='benefits', max_length=250, verbose_name='id (don"t touch'),
        ),
    ]
