# Generated by Django 5.2.1 on 2025-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0033_heroblock_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroblock',
            name='slug',
            field=models.SlugField(blank=True, default='hero', max_length=250, verbose_name='id'),
        ),
    ]
