# Generated by Django 5.2.1 on 2025-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0034_alter_heroblock_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateblock',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='clientsblock',
            name='slug',
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='slug',
            field=models.SlugField(blank=True, default='about', max_length=250),
        ),
        migrations.AlterField(
            model_name='casesblock',
            name='slug',
            field=models.SlugField(blank=True, default='cases', max_length=250),
        ),
        migrations.AlterField(
            model_name='faqblock',
            name='slug',
            field=models.SlugField(blank=True, default='faq', max_length=250),
        ),
        migrations.AlterField(
            model_name='solutionsblock',
            name='slug',
            field=models.SlugField(blank=True, default='solutions', max_length=250),
        ),
        migrations.AlterField(
            model_name='tariffblock',
            name='slug',
            field=models.SlugField(blank=True, default='tariffs', max_length=250),
        ),
    ]
