# Generated by Django 5.2.1 on 2025-07-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0035_remove_certificateblock_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffblock',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
