# Generated by Django 5.2.1 on 2025-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0036_tariffblock_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Сделать главной страницей'),
        ),
    ]
