# Generated by Django 5.2.1 on 2025-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0037_landingpage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='seotitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
