# Generated by Django 5.2.1 on 2025-07-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0038_landingpage_seotitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='seodescription',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
