# Generated by Django 5.2.1 on 2025-07-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_name_alter_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Источник'),
        ),
    ]
