# Generated by Django 5.2.1 on 2025-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, default='Contact us', max_length=255, verbose_name='Contact us'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='Contacts', max_length=255),
        ),
    ]
