# Generated by Django 5.2.1 on 2025-07-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_alter_contact_title_alter_content_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='name',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
