# Generated by Django 5.2.1 on 2025-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_remove_contact_content_remove_phones_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map',
            field=models.CharField(blank=True, default='put the link here', max_length=255),
        ),
    ]
