# Generated by Django 5.2.1 on 2025-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='svg_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
